Task1/Task1/Models/Database/Departments.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace Task1.Models.Database
{
    public class Departments
    {
        SqlConnection conn;

        public Departments(SqlConnection conn)
        {
            this.conn = conn;
        }
        public List<Department> GetAll()
        {
            List<Department> departments = new List<Department>();
            string query = "select * from Departments";
            SqlCommand cmd = new SqlCommand(query, conn);
            conn.Open();
            SqlDataReader reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                Department d = new Department()
                {
                    Id = reader.GetInt32(reader.GetOrdinal("Id")),
                    Name = reader.GetString(reader.GetOrdinal("Name")),
                    
                };
                departments.Add(d);
            }
            conn.Close();
            return departments;
        }
    }
}

Task1/Task1/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Task1.Models
{
    public class Department
    {
        public int Id { get; set; }
       
        public string Name { get; set; }
        public List<Student> Students { get; set; }
      //  public List<Department> Departments { get; internal set; }
      //  public Student Student { get; internal set; }
    }
}

Task1/Task1/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task1.Models;
using Task1.Models.Database;

using Task1.Models.ViewModel;

namespace Task1.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Dashboard()
        {
            // Database db = new Database();
           // var students = db.Students.GetAll();
            //return View(students);

           
            Database db = new Database();
            StudentDepartment combodata = new StudentDepartment();
            //Department combodata = new Department();
           // var students = db.Students.GetAll();
            combodata.Departments = db.Departments.GetAll();
            combodata.Students = db.Students.GetAll();
            return View(combodata);
        }
        public ActionResult Department()
        {
            Database db = new Database();
            var departments = db.Departments.GetAll();
          
            return View(departments);
        }
        public ActionResult Create()
        {
            Student s = new Student();
            Database db = new Database();
            StudentDepartment combodata = new StudentDepartment();
            //Department combodata = new Department();
            combodata.Student = s;
            combodata.Departments= db.Departments.GetAll();
            //dynamic combodata = new ExpandoObject();
            //combodata.Student = p;

            //combodata.Departments = db.Departments.GetAll();
            return View(combodata);
            
        }
        [HttpPost]
        public ActionResult Create(Student s)
        {
            //insert to db
            if (ModelState.IsValid)
            {
                Database db = new Database();
                db.Students.Insert(s);
                return RedirectToAction("Dashboard");
            }
            return View();

        }
        public ActionResult Edit(int id)
        {

            Database db = new Database();
            var s = db.Students.Get(id);

            return View(s);
        }
        [HttpPost]
        public ActionResult Edit(Student s)
        {
            //update to db
            Database db = new Database();
            db.Students.Update(s);
            return RedirectToAction("Dashboard");
        }


        public ActionResult Delete(int id)
        {
            //insert to db
            // if (ModelState.IsValid)
            //{
            Database db = new Database();
            db.Students.Delete(id);
            return RedirectToAction("Dashboard");
            // }
            //return View();

        }
        [HttpPost]
        public ActionResult Login(Admin a)
        {
            if (ModelState.IsValid)
            {
                //Admins db = new Admins();
               //bool v= db.loginValidate(a.UserName, a.Password);
                string connString = @"Server=.\sqlexpress;Database=ANet;Integrated Security=true;";
                SqlConnection conn1 = new SqlConnection(connString);
                string query = $"select * from Admins";
                SqlCommand cmd = new SqlCommand(query, conn1);
                conn1.Open();
                SqlDataReader reader = cmd.ExecuteReader();

                while (reader.Read())
                {

                    int Id = reader.GetInt32(reader.GetOrdinal("Id"));
                    string Name = reader.GetString(reader.GetOrdinal("Name"));
                    string UserName = reader.GetString(reader.GetOrdinal("UserName"));
                    string Password = reader.GetString(reader.GetOrdinal("Password"));
                    if (a.Password==Password && a.UserName==UserName)
                    {
                        return RedirectToAction("Dashboard");
                    }
                    else {
                        ViewBag.Message = "invalid  Username or password.";
                        return View(); 
                    
                    }
                }
                
               
            }
            return View();
           
        }
    }
}

Task1/Task1/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Task1.Controllers
{
    public class DepartmentController : Controller
    {
        // GET: Department
        public ActionResult Index()
        {
            return View();
        }
    }
}

Task1/Task1/Views/Admin/Create.cshtml
@model Task1.Models.ViewModel.StudentDepartment
@{
    ViewBag.Title = "Create";
}

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Students", "Dashboard", "Admin")</li>
                <li>@Html.ActionLink("Create Students", "Create", "Admin")</li>
                <li>@Html.ActionLink("Depatmrnts", "Department", "Admin")</li>
            </ul>
        </div>
    </div>
</div>

<h2>Create</h2>

<div>
    <form action="/Admin/Create" method="post">
        <select name="Dept_Id" class="form-control">
            <option value="null" selected disabled>--Select--</option>
            @foreach (var c in Model.Departments)
            {
                <option value="@c.Id">@c.Name</option>
            }
        </select>
        @Html.ValidationMessageFor(model => Model.Student.Dept_Id, "", new { @class = "span" })

        <input type="text" name="Name" class="form-control" placeholder="name..">
        @Html.ValidationMessageFor(model => Model.Student.Name, "", new { @class = "span" })
        <input type="date" name="DOB" class="form-control" placeholder="">
        @Html.ValidationMessageFor(model => Model.Student.DOB, "", new { @class = "span" })
        <input type="text" name="Credit" class="form-control" placeholder="ctrdit..">
        @Html.ValidationMessageFor(model => Model.Student.Credit, "", new { @class = "span" })
        <input type="number" name="CGPA" class="form-control" placeholder="cgpa.." step="any">
        @Html.ValidationMessageFor(model => Model.Student.CGPA, "", new { @class = "span" })
        <input type="submit" class="btn btn-block" value="Add" />
    </form>
</div>

Task1/Task1/Views/Admin/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
}
@model Task1.Models.ViewModel.StudentDepartment

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Students", "Dashboard", "Admin")</li>
                <li>@Html.ActionLink("Create Students", "Create", "Admin")</li>
                <li>@Html.ActionLink("Depatmrnts", "Department", "Admin")</li>
            </ul>
        </div>
    </div>
</div>

<div class="container">
    <table class="table table-condensed">
        <tr>
            <th>Id</th>
            <th>Department Name</th>
            <th>Name</th>
            <th>Date Of Birth</th>
            <th>Credit</th>
            <th>CGPA</th>
            <th></th>
            <th></th>
        </tr>
        @foreach (var student in @Model.Students)
        {
    <tr>
        <td>@student.Id</td>
        @foreach (var dept in @Model.Departments)
        {
            { 
            if (student.Dept_Id == dept.Id)
            {
                <td>@dept.Name</td>
            }
            }
        }
        <td>@student.Name</td>

        <td>@student.DOB</td>
        <td>@student.Credit</td>
        <td>@student.CGPA</td>
        <td><a class="btn btn-success" href="/Admin/Edit/@student.Id">Edit</a></td>
        <td><a class="btn btn-danger" href="/Admin/Delete/@student.Id">Delete</a> </td>
    </tr>
        }

    </table>
</div>

Task1/Task1/Views/Admin/Department.cshtml
@{
    ViewBag.Title = "Department";
}

@model  List<Task1.Models.Department>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Students", "Dashboard", "Admin")</li>
                <li>@Html.ActionLink("Create Students", "Create", "Admin")</li>
                <li>@Html.ActionLink("Depatmrnts", "Department", "Admin")</li>
            </ul>
        </div>
    </div>
</div>
<div class="container">
    <table class="table table-condensed">
        <tr>
            <th>Id</th>
            <th>Department Name</th>
            
        </tr>
        @foreach (var dept in @Model)
        {
            <tr>
                <td>@dept.Id</td>
                <td>@dept.Name</td>
               
                
            </tr>
        }
        </table>
        </div>

Task1/Task1/Views/Admin/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

@model Task1.Models.Student

div class="navbar navbar-inverse navbar-fixed-top">
<div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Students", "Dashboard", "Admin")</li>
            <li>@Html.ActionLink("Create Students", "Create", "Admin")</li>
            <li>@Html.ActionLink("Depatmrnts", "Department", "Admin")</li>
        </ul>
    </div>
</div>

<h2>Edit</h2>
<div>
    <form action="" method="post">
        <input type="hidden" name="Id" value="@Model.Id">
        <input type="hidden" name="Dept_Id" class="form-control"  value="@Model.Dept_Id" >
        <input type="text" name="Name" value="@Model.Name" class="form-control" placeholder="name..">
        <input type="date" name="DOB"  value="@Model.DOB" class="form-control" placeholder="">
        <input type="text" name="Credit"  value="@Model.Credit" class="form-control" placeholder="ctrdit..">
        <input type="number" name="CGPA" value="@Model.CGPA" step="any" class="form-control" placeholder="cgpa..">
        <input type="submit" class="btn btn-block" value="Edit" />
    </form>
</div>

Task1/Task1/Views/Admin/Login.cshtml
@{
    ViewBag.Title = "Login";
}
@model Task1.Models.Admin
<h2>Login</h2>
<div>
    <form action="" method="post">

        <input type="text" name="UserName" class="form-control" placeholder="username">
        @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        <input type="password" name="Password" class="form-control" placeholder="Password..">
        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
    <span class="text-danger"> @ViewBag.Message</span>

        <input type="submit" class="btn btn-block" value="Login" />
    </form>
</div>